# Training profile: CPU-first (single host)
# Goal: Enable viable training on CPU for the ~80M encoder with Leafy Chain + HGAT

run:
  seed: 1337
  epochs: 5
  gradient_accumulation_steps: 64  # compensate for micro-batch=1
  log_interval: 50
  eval_interval_steps: 2000
  save_interval_steps: 5000
  mixed_precision: false  # CPU BF16 availability varies; default to fp32
  deterministic: true

hardware:
  device: cpu
  num_workers: 4   # dataloader workers
  pin_memory: false

model:
  hidden_size: 768
  num_layers: 12
  num_heads: 12
  intermediate_size: 3072
  dropout: 0.1
  positional_encoding: alibi  # CPU-friendly
  norm: rmsnorm
  activation: swiglu
  hgat:
    enabled: true
    relation_bias: true
  use_rel_attention_bias: true  # Validated: 50% MNM improvement in ablation

optimizer:
  name: adamw
  lr: 2.5e-4
  weight_decay: 0.01
  betas: [0.9, 0.98]
  eps: 1e-8
  scheduler:
    name: cosine
    warmup_steps: 2000

training_data:
  max_seq_len: 512   # CPU budget; ramp later if needed
  micro_batch_size: 1
  pack_sequences: true
  short_to_long_curriculum:
    enabled: true
    schedule:
      - {steps: 0, max_seq_len: 384}
      - {steps: 20000, max_seq_len: 512}

objectives:
  mlm:
    mask_prob: 0.15
    span_mask_identifiers: true
  mnm:
    mask_prob: 0.20
    type_consistent_negatives: 2
    hard_negatives: 1

encoding:
  leaves_per_anchor:
    positive: 2
    negatives: 2
  max_leaves_per_sequence: 8

regularizers:
  ontology_constraints:
    antisymmetry_weight: 0.2
    acyclicity_weight: 0.2
  contrastive:
    enabled: true
    temperature: 0.07

checkpointing:
  activation_checkpointing: true  # recompute on CPU is cheap vs memory
  gradient_checkpointing: true

notes:
  - CPU-first: expect slow wall-clock; use high grad_accum and sequence packing.
  - Prefer running overnight; keep eval small and frequent to catch regressions.
