run:
  seed: 42
  mixed_precision: fp16
  run_name: "mnm_fixed_v1"

hardware:
  device: cpu  # Change to gpu for production

model:
  hidden_size: 768
  num_layers: 12
  num_heads: 12
  intermediate_size: 3072
  use_rel_attention_bias: true

optimizer:
  encoder_lr: 3.0e-4
  mnm_head_lr: 5.0e-4
  weight_decay: 0.01

training_data:
  micro_batch_size: 2
  grad_accumulation_steps: 4
  max_seq_len: 128

# MNM-specific tuning
mnm:
  loss_weight: 0.2
  weight_ramp_steps: 500
  mask_min: 8
  freeze_encoder_steps: 100

checkpointing:
  save_every_steps: 200
